//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gh
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashRegisters
    {
        public int ID_CashRegisters { get; set; }
        public string Location_ { get; set; }
        public Nullable<decimal> CashBalance { get; set; }
    }
}
