//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gh
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employees
    {
        public int ID_Employees { get; set; }
        public string FirstName { get; set; }
        public string Surname { get; set; }
        public string MidName { get; set; }
        public Nullable<int> Role_ID { get; set; }
    
        public virtual Roles Roles { get; set; }
    }
}
