//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gh
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory
    {
        public int ID_Inventory { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> QuantityInStock { get; set; }
    
        public virtual Products Products { get; set; }
    }
}
