//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gh
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductSuppliers
    {
        public Nullable<int> Product_ID { get; set; }
        public Nullable<int> Supplier_ID { get; set; }
        public int ID_ProductSuppliers { get; set; }
    
        public virtual Products Products { get; set; }
        public virtual Suppliers Suppliers { get; set; }
    }
}
